name: Output

on:
  # push:
    # branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: execute py script # aggregate current data
            run: |
              python -m pip install -r requirements.txt
              python relative-strength.py true false ${{ secrets.API_KEY }}
          - name: push to log git
            run: |
              git clone https://zklee98:${{ secrets.PAT }}@github.com/zklee98/rsrating_output.git
              rm ./rsrating_output/output/* && cp -a ./output/. ./rsrating_output/output
              cd rsrating_output
              git config user.name "CI" && git config user.email "ci@github.com"
              git add --all
              git commit -m "CI output update" || echo "nothing to commit"
              git push || echo "nothing to push"
          # - uses: actions/upload-artifact@v2
          #   with:
          #     name: rs_stocks.csv
          #     path: output
